config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  resources :clients
  resources :notifications
  resources :notes

  get 'birthday', to: 'clients#birthday'
  devise_for :users


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord

  has_many :notes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, -> { where notification: false },
                              dependent: :destroy

 validates :name, presence: true, length: { minimum: 3 }
 validates :email, uniqueness: true


def self.birthday
  m = Time.now.month

  Client.where('extract(month from birthday) = ?', m )
  
end

def self.list_notification
  @notificar = Notification.where(notification: 0)
end


end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :client
  validates :title, presence: true
  validates :messager, presence: true

end

app/models/notification.rb
class Notification < ApplicationRecord
 
  belongs_to :client
  
  # Validation Notification
 validates :title, presence: true, length: {minimum:3, maximum:250}
 validates :calendar, presence: true
 validates :messager, presence: true, length: {minimum:5, maximum:500}
  
def self.sending

  @datenow = Time.now
  @notif = Notification.where("calendar < ?", @datenow)
  @notif.update(notification: 1)

  @notification = Notification.where("updated_at >= ?", @datenow.ago(10.minute) )
 
# Sender notification for email now
  @notification.each do |sender|
    NotificationMailer.send_notification(sender.client.email,
    sender.title, sender.messager).deliver_now
  end

end

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ROLES = %i[user admin banned ]
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  layout :template_resource
  helper :all

  private

    def template_resource
      if user_signed_in? == false
      "login"
      else
      "application"
      end
    end


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :set_client, only: [:show, :edit, :update, :destroy]
  # GET /clients
  def index

    @client =  Client.all

  end



  # GET /clients/1
  def show
    @notes =  @client.notes
  end

  # GET /clients/new
  def new

    @client = Client.new

  end

  # GET /clients/1/edit
  def edit

  end

  # POST /clients    @notes = @client.notes.create(params[:title, :messager])


  def create

    @client = Client.new(client_params)


    if @client.save
      redirect_to clients_path, notice: 'Novo cliente foi criado com sucesso'
    else
      flash.now[:alert] = @client.errors.full_messages.to_sentence
      render :new
    end

  end

  # PATCH/PUT /clients/1
  def update

    if @client.update(client_params)
      redirect_to client_path, notice: 'Cliente atualizado com sucesso'
    else
      render :edit
    end

  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, alert: 'Cliente foi deletado com sucesso.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end



    def client_params
      params.require(:client).permit(:name, :last_name, :email, :cep, :address, :birthday, :tel, :cel, :cpf)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
    

    

end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

before_action :set_notes, only: [:edit, :update, :destroy, :show]

# GET /notify
def index

end

# GET /notify/new
def new

end

# POST /notes
def create

   @notes = Note.new(notes_params)

   if @notes.save
     redirect_to client_path(@notes.client_id), notice: "Anotação realizada com sucesso!"
   else
      redirect_to client_path(@notes.client_id), alert: "Não foi possivel realizar a anotação #{ @notes.errors.full_messages}"
   end

end

# GET /notify/:id/show
def show

end

def update
  #code
end
# GET /notify/:id/edit
def edit
  #code
end

# GET /notify/:id
def destroy
  if @notes.destroy
  redirect_to client_path(@notes.client_id), alert: "Anotação foi deletado com sucesso"
  else
  flash.now[:alert] = @notes.errors.full_messages.to_sentence
  render :show
  end
end

private

def set_notes
  @notes = Note.find(params[:id])
end

def notes_params
  params.require(:note).permit(:title, :messager, :client_id)
end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  
  before_action :set_notifications, only: [:edit, :destroy, :update, :show]
  
  
  # Get /notification/
  def index
    
    @notification = Notification.where(notification: 0)
    @notification_send = Notification.where(notification: 1)
    
  end
  
  # Get /notification/new
  def new
    # Send notification for email client
    @client = Client.find(params[:user])
    @notification = @client.notifications.new
    
  end
  
  # Post /notifications
  def create
    @notification = Notification.new(notifications_params)
    
    if @notification.save
      redirect_to notifications_path, notice: "Notificação foi criada com sucesso"
    else
      redirect_to new_notification_path(user: @notification.client_id), alert: @notification.errors.full_messages.to_sentence
    end
  end
  
  def destroy
    if @notification.destroy
      redirect_to notifications_path, alert: "Notificação foi deletado com sucesso"
    else
      render :index, alert: "Não foi possível deletar está notificação"
    end
  end
  
  def edit
    
  end
  
  def update
    
    if @notification.update(notifications_params)
      redirect_to notifications_path, notice: "Notificação atualizada com sucesso"
    else
      flash[:alert] = @notification.errors.full_messages.to_sentence
      render :edit
    end
  end
  
  
  private
  
  def set_notifications
    @notification = Notification.find(params[:id])
  end
  
  def notifications_params
    params.require(:notification).permit(:title, :messager, :calendar, :client_id)
  end
  
end

app/controllers/notify_controller.rb
class NotifyController < ApplicationController

before_action :set_notify, only: [:edit, :update, :destroy, :create]

# GET /notify
def index

end

# GET /notify/new
def new
   
end

def create
  #code
end

# GET /notify/:id/show
def show

end

def update
  #code
end
# GET /notify/:id/edit
def edit
  #code
end

# GET /notify/:id
def destroy
  #code
end

private

def set_notify
  @notify = Notify.find(params[:id])
end

def notify_params
  params.require(:notify).permit(:title, :messager, :delivery, :send, :client_id)
end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

before_action :params_device, if: :devise_controller?

  private
  def params_device
    added_attrs = [:name, :last_name, :email, :password, :password_confirmation, :remember_me, :role]

    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
     content_for(:title){ page_title }
     page_title
   end
 

  def saudacao
    timenow = Time.now.hour
    case timenow
      when 0..11
        "<b>Bom dia!</b> #{current_user.name}".html_safe
      when 12..17
        "<b>Boa tarde!</b> #{current_user.name}".html_safe
      when 18..23
        "<b>Boa noite!</b> #{current_user.name}".html_safe
      end

  end


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notify_helper.rb
module NotifyHelper
end

app/helpers/onsignal_helper.rb
module OnsignalHelper


def notification

client = OneSignal::Client.new(auth_token: 'YTFmZmQ0MjQtNmRkYy00MTM3LWFjNGMtNGU5NTIxNWNkZjBj', app_id: 'ffc48929-efe2-494c-a3ce-8e23528623f8')
# params = {"app_id" => "f25ce7ac-9737-4b46-af9a-42c20444cf12",
#          "headings" => {"en"=> title},
#           "chrome_web_icon" => picture,
#           "contents" => {"en" => content},
#           "send_after" => deliver,
#           "included_segments" => ["All"]}
#
# client.notifications.create(params)

end

end

app/views/clients/edit.html.erb
<% title('Editar') %>

<%= render 'form', client: @client %>


 

app/views/clients/index.html.erb
  <!-- Page Heading -->
  <%# <h1 class="h3 mb-2 text-gray-800">Gerenciar Clientes</h1> %>
  <%# <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p> %>

  <!-- DataTales Example -->
  <div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary"><%= title('Gerenciar Clientes') %></h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">

      
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Notificações</th>
              <th>Nome</th>
              <th>E-mail</th>
              <th>Aniversário: </th>
              <th>Anotações  : </th>
              <th>Ação</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>Notificações</th>
              <th>Nome</th>
              <th>E-mail</th>
              <th>Aniversário:</th>
              <th>Anotações:</th>
              <th>Ação</th>
            </tr>
          </tfoot>
          <tbody>
            <% @client.each do |c| %>
            <tr>
              <td>
                <a href="<%= new_notification_path(user: c.id) %>" class="btn btn-outline-success">Enviar</a>
              </td>
              <td>
                <b><%= c.name %></b>
              </td>
              <td><%= c.email %></td>
              <td><%= c.birthday.strftime("%d/%m/%Y") %></td>
              <td><span class="badge badge-info"><%= c.notes.size %></span></td>

              <td>
                <%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe , edit_client_path(c), class: 'btn btn-sm btn-primary' %>
                <%= link_to '<i class="fa fa-file-alt"></i> Detalhes'.html_safe , client_path(c), class: 'btn  btn-sm btn-info' %>

                <%= link_to "<i class='fa fa-trash' ></i> Delete".html_safe,
                    client_path(c),
            method: :delete, data: { confirm: 'Você realmente deseja deletar ?' }, class: "btn btn-danger  btn-sm"  %>


              </td>
            </tr>
            <% end %>


          </tbody>
        </table>


      </div>
    </div>
  </div>

</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->

app/views/clients/new.html.erb
 <% title('Adicionar Novo') %>
   
<%= render 'form', client: @client %>

app/views/clients/show.html.erb
  <div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary"><%= title('Dados do clientes - ') + @client.name  %></h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
            <div class="card-body">
            <span class="pb-2 display-5"><b>Nome:</b> <%= @client.name + ' ' + @client.last_name %></span> <br>
            <span class="pb-2 display-5"><b>E-mail:</b> <%= @client.email %> </span> <br>
            <span class="pb-2 display-5"><b>Telefone:</b> <%= @client.tel %> </span> <br>
            <span class="pb-2 display-5"><b>Celular:</b> <%= @client.cel %> </span> <br>
            <span class="pb-2 display-5"><b>Cpf:</b> <%= @client.cpf %> </span> <br>
            <span class="pb-2 display-5"><b>Endereço:</b> <%= @client.address %> </span><br>
            <span class="pb-2 display-5"><b>Aniversário:</b> <%= @client.birthday.strftime("%d/%m/%Y") %> </span>
        <p></p>
            <span class="pb-2 display-5">
             <%= link_to '<i class="fas fa-paper-plane"></i> Enviar Notificação'.html_safe, new_notification_path(user: @client.id), class: "btn btn-success" %>
            </span>
          </div>
       </div>
     </div>
  


 <div class="card-body">
 <h4> <span style="color:#dd0042" "> <i class="fas fa-clipboard-list fa-lg"></i></span> Anotações para cliente</h4>
 <hr>
 <ul class="nav flex-column">
  <% @notes.each do |note| %>
     <li class="nav-item">
        <div class="card mb-3 py-3 border-left-info">
        
              <div class="card-body">

     <h4><%= note.title %> </h4>
                    <span class="text-sm-left text-muted "> <i class="fa fa-history" aria-hidden="true"></i> <%= time_ago_in_words(note.created_at) %></span>
        <div class="d-flex align-items-end flex-column">

        <%= link_to "<i class='fas fa-trash-alt'></i> Deletar".html_safe, note_path(note), metho: :delete, data: {confirm:"Desejar deletar essa nota?"}, class: 'btn-danger btn btn-sm text-right'  %>
        </div>     
                   
         
              
                  <%= note.messager %>
              </div>
            </div>
          </div>
     </li>
   
 </ul>
 
   

 </div>

<% end %>




<%= render "notes/form", notes: @notes %>



 
       

app/views/home/index.html.erb
<% title('Dashboard') %>

    <!-- Right Panel -->
 
 


            <!--/.col-->
  <%= render 'clients/birthday'  %>


            <!--/.col-->


            <!--/.col-->



            <!-- <div class="col-xl-3 col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <div class="stat-widget-one">
                            <div class="stat-icon dib"><i class="ti-money text-success border-success"></i></div>
                            <div class="stat-content dib">
                                <div class="stat-text">Total Profit</div>
                                <div class="stat-digit">1,012</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> -->




 

app/views/notifications/edit.html.erb
 
<%= render 'form', notification: @notification %>

app/views/notifications/index.html.erb
<div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary"><%= title('Gerenciar Notificações') %></h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">


        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Titulo:</th>
              <th>Para:</th>
              <th>Agendado em:</th>
              <th>Anotações do cliente:</th>
              <th>Ação</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>Titulo:</th>
              <th>Para:</th>
              <th>Agendado em:</th>
              <th>Anotações do cliente:</th>
              <th>Ação</th>
            </tr>
          </tfoot>
          <tbody>

            <% @notification.each do |notification| %>

            <tr>
              <td><%= notification.title %></td>
              <td><b><%= notification.client.name %></b></td>
              <td><span class="badge badge-info">
                  <%= notification.calendar.strftime("%d/%m/%Y %-l:%M %P") %> </span> </td>
              <td>

                <% if notification.client.notes.size > 0  %>
                <span class="badge badge-info"> <%= notification.client.notes.size %> </span>
                <a href="<%= client_path(notification.client.id) %>"   class="btn btn-primary btn-sm">
                  <i class="fa fa-plus" aria-hidden="true"></i>  add anotação </a> 
          
              
                <% else %>
             <span class="text-center">
                nenhuma anotação até o momento. <br> <%= link_to "Criar anotação", client_path(notification.client.id) %>
             </span>
                <% end %>
              </td>
              <td>

                <%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_notification_path(notification), class: "btn btn-info btn-sm" %>
                <%= link_to '<i class="fa fa-trash btn-sm"></i> Excluir'.html_safe , notification_path(notification), method: :delete, data: {confirm: "Deseja deletar esse item?"}, class: "btn btn-danger btn-sm" %>
              </td>
              </td>
              <% end %>

          </tbody>
        </table>
<p></p>
        <ul class="list-group">
          <li class="list-group-item"> <strong class="card-title font-weight-bold">Notificações
              enviadas</strong></li>

          <% @notification_send.each do |sender| %>

          <li class="list-group-item list-group-item-light"> <%= link_to "<i class='fa fa-trash'></i>".html_safe, notification_path(sender),
method: :delete, data: {confirm: "Deseja deletar esse item?"}, class: "btn btn-xs btn-danger text-right" %>  <b><%= sender.client.name %></b> - 
 <%= sender.title %> -
              Enviado:  <i class="fa fa-clock" aria-hidden="true"></i> <%= time_ago_in_words(sender.calendar) %> 
            </li>
          <% end %>
        </ul>


      </div>
    </div>
  </div>

</div>
<!-- /.container-fluid -->

</div>
</div>
</div>

app/views/notifications/new.html.erb
 
<%= render 'form', notification: @notification %>

app/views/shered/_sidebar.html.erb
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"> <%= t('company_name') %> <sup><%= t('version') %></sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span><%= t('Dashboard') %></span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Notify
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Clientes</span>
        </a>
           <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gerenciar clientes:</h6>
            <a class="collapse-item" href="<%= clients_path %>">Lista de Clientes</a>
            <a class="collapse-item" href="<%= new_client_path %>">Add novo Clientes</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" 
            data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-bell"></i>
          <span>Notificações</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" 
        data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Gerenciar notificações</h6>
            <a class="collapse-item" href="<%= notifications_path %>">Lista de Notificação</a>
           
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <%# <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="login.html">Login</a>
            <a class="collapse-item" href="register.html">Register</a>
            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="404.html">404 Page</a>
            <a class="collapse-item" href="blank.html">Blank Page</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Charts -->
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li> %>

      <!-- Divider -->
      <%# <hr class="sidebar-divider d-none d-md-block"> %>

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

app/views/shered/header/_nav_left.html.erb
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">

        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse"
             data-target="#main-menu" aria-controls="main-menu" aria-expanded="false"
             aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<%= root_path %>"> <h4>Notify Custumers</h4></a>
            <a class="navbar-brand hidden" href="./"><h4>NC</h4></a>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<%= root_path %>"> <i class="menu-icon fa fa-dashboard"></i>Principal </a>
                </li>
                <h3 class="menu-title">Clientes</h3><!-- /.menu-title -->
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false"> <i class="menu-icon fa fa-laptop"></i>Gerenciar Clientes</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-list"></i><a href="">Listar Clientes</a></li>
                        <li><i class="fa fa-plus-circle"></i><%= link_to 'Novo Cliente', new_client_path %></li>


                        <!-- <li><i class="fa fa-id-badge"></i><a href="ui-badges.html">Lorem ipson</a></li>
                        <li><i class="fa fa-bars"></i><a href="ui-tabs.html">Lorem ipson</a></li>
                        <li><i class="fa fa-share-square-o"></i><a href="ui-social-buttons.html">Lorem ipson</a></li>
                        <li><i class="fa fa-id-card-o"></i><a href="ui-cards.html">Lorem ipson</a></li> -->
                        <!-- <li><i class="fa fa-exclamation-triangle"></i><a href="ui-alerts.html">Alerts</a></li>
                        <li><i class="fa fa-spinner"></i><a href="ui-progressbar.html">Progress Bars</a></li>
                        <li><i class="fa fa-fire"></i><a href="ui-modals.html">Modals</a></li>
                        <li><i class="fa fa-book"></i><a href="ui-switches.html">Switches</a></li>
                        <li><i class="fa fa-th"></i><a href="ui-grids.html">Grids</a></li>
                        <li><i class="fa fa-file-word-o"></i><a href="ui-typgraphy.html">Typography</a></li> -->
                    </ul>
                </li>
                <!-- <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Tables</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-table"></i><a href="tables-basic.html">Basic Table</a></li>
                        <li><i class="fa fa-table"></i><a href="tables-data.html">Data Table</a></li>
                    </ul>
                </li> -->
                <!-- <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Forms</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-th"></i><a href="forms-basic.html">Basic Form</a></li>
                        <li><i class="menu-icon fa fa-th"></i><a href="forms-advanced.html">Advanced Form</a></li>
                    </ul>
                </li> -->

                <h3 class="menu-title">Sistema Notify</h3><!-- /.menu-title -->

             <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bell-o"></i>Notificações</a>
                    <ul class="sub-menu children dropdown-menu">

                        <li><i class="fa fa-list"></i><a href="<%= notifications_path %>">Notificações</a></li>
                        <li><i class="fa fa-table"></i><a href="tables-data.html">Data Table</a></li>
                    </ul>
                </li>


                <!-- <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Charts</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-line-chart"></i><a href="charts-chartjs.html">Chart JS</a></li>
                        <li><i class="menu-icon fa fa-area-chart"></i><a href="charts-flot.html">Flot Chart</a></li>
                        <li><i class="menu-icon fa fa-pie-chart"></i><a href="charts-peity.html">Peity Chart</a></li>
                    </ul>
                </li> -->

                <!-- <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-area-chart"></i>Maps</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-map-o"></i><a href="maps-gmap.html">Google Maps</a></li>
                        <li><i class="menu-icon fa fa-street-view"></i><a href="maps-vector.html">Vector Maps</a></li>
                    </ul>
                </li> -->
                <h3 class="menu-title">Configurações Extras</h3><!-- /.menu-title -->



           <li class="menu-item-has-children dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-user"></i>Minha Conta</a>
                  <ul class="sub-menu children dropdown-menu">
             
                      <li><i class="fa fa-user-o"></i><a href="<%= edit_user_registration_path %>">Conta</a></li>
                      <li><i class="fa fa-sign-in"></i><a href="tables-data.html">Sair</a></li>
                  </ul>
              </li>


                <li class="menu-item-has-children dropdown">

                    <!-- <ul class="sub-menu children dropdown-menu">
                        <li><i class="menu-icon fa fa-sign-in"></i><a href="page-login.html">Login</a></li>
                        <li><i class="menu-icon fa fa-sign-in"></i><a href="page-register.html">Register</a></li>
                        <li><i class="menu-icon fa fa-paper-plane"></i><a href="pages-forget.html">Forget Pass</a></li>
                    </ul> -->
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside><!-- /#left-panel -->